# Pandas Exercises

In [1]:
import pandas as pd

url = "https://raw.githubusercontent.com/BeaverWorksMedlytics2020/Data_Public/master/NotebookExampleData/Week1/diabetes.csv"
names = ['preg', 'plas', 'pres', 'skin', 'test', 'mass', 'pedi', 'age', 'class']

Read in csv above to a pandas dataframe

In [2]:
# YOUR CODE HERE
df = pd.read_csv(url, names = names)
df

     preg  plas  pres  skin  test  mass   pedi  age  class
0       6   148    72    35     0  33.6  0.627   50      1
1       1    85    66    29     0  26.6  0.351   31      0
2       8   183    64     0     0  23.3  0.672   32      1
3       1    89    66    23    94  28.1  0.167   21      0
4       0   137    40    35   168  43.1  2.288   33      1
..    ...   ...   ...   ...   ...   ...    ...  ...    ...
763    10   101    76    48   180  32.9  0.171   63      0
764     2   122    70    27     0  36.8  0.340   27      0
765     5   121    72    23   112  26.2  0.245   30      0
766     1   126    60     0     0  30.1  0.349   47      1
767     1    93    70    31     0  30.4  0.315   23      0

[768 rows x 9 columns]

Print out the age and class of the 100th patient

In [3]:
# YOUR CODE HERE



df.loc[99, ['age', 'class']]

age      31.0
class     1.0
Name: 99, dtype: float64

Write code to figure out how many people are classified as not having diabetes, class is 0

In [4]:
# YOUR CODE HERE

df.loc[df['class'] == 0]

     preg  plas  pres  skin  test  mass   pedi  age  class
1       1    85    66    29     0  26.6  0.351   31      0
3       1    89    66    23    94  28.1  0.167   21      0
5       5   116    74     0     0  25.6  0.201   30      0
7      10   115     0     0     0  35.3  0.134   29      0
10      4   110    92     0     0  37.6  0.191   30      0
..    ...   ...   ...   ...   ...   ...    ...  ...    ...
762     9    89    62     0     0  22.5  0.142   33      0
763    10   101    76    48   180  32.9  0.171   63      0
764     2   122    70    27     0  36.8  0.340   27      0
765     5   121    72    23   112  26.2  0.245   30      0
767     1    93    70    31     0  30.4  0.315   23      0

[500 rows x 9 columns]

Write code to figure out how many people are classified as having diabetes, class is 1

In [5]:
# YOUR CODE HERE

df.loc[df['class'] == 1]

     preg  plas  pres  skin  test  mass   pedi  age  class
0       6   148    72    35     0  33.6  0.627   50      1
2       8   183    64     0     0  23.3  0.672   32      1
4       0   137    40    35   168  43.1  2.288   33      1
6       3    78    50    32    88  31.0  0.248   26      1
8       2   197    70    45   543  30.5  0.158   53      1
..    ...   ...   ...   ...   ...   ...    ...  ...    ...
755     1   128    88    39   110  36.5  1.057   37      1
757     0   123    72     0     0  36.3  0.258   52      1
759     6   190    92     0     0  35.5  0.278   66      1
761     9   170    74    31     0  44.0  0.403   43      1
766     1   126    60     0     0  30.1  0.349   47      1

[268 rows x 9 columns]

What percent of people have diabetes in the study

In [6]:
# YOUR CODE HERE

df.loc[df['class'] == 1].shape[0] / df.shape[0]

0.3489583333333333

Print out the `"pres"` and `"class"` (no other columns) for the first 5 people

In [9]:
# YOUR CODE HERE

df[['pres', 'class']].head()

   pres  class
0    72      1
1    66      0
2    64      1
3    66      0
4    40      1

Run the cell below, it will print out the correlation among the columns

In [11]:
df.corr()

,preg,plas,pres,skin,test,mass,pedi,age,class
preg,1.000000,0.129459,0.141282,-0.081672,-0.073535,0.017683,-0.033523,0.544341,0.221898
plas,0.129459,1.000000,0.152590,0.057328,0.331357,0.221071,0.137337,0.263514,0.466581
pres,0.141282,0.152590,1.000000,0.207371,0.088933,0.281805,0.041265,0.239528,0.065068
skin,-0.081672,0.057328,0.207371,1.000000,0.436783,0.392573,0.183928,-0.113970,0.074752
test,-0.073535,0.331357,0.088933,0.436783,1.000000,0.197859,0.185071,-0.042163,0.130548
mass,0.017683,0.221071,0.281805,0.392573,0.197859,1.000000,0.140647,0.036242,0.292695
pedi,-0.033523,0.137337,0.041265,0.183928,0.185071,0.140647,1.000000,0.033561,0.173844
age,0.544341,0.263514,0.239528,-0.113970,-0.042163,0.036242,0.033561,1.000000,0.238356
class,0.221898,0.466581,0.065068,0.074752,0.130548,0.292695,0.173844,0.238356,1.000000

What column has the highest correlation with class? Find the mean() value of that column

In [12]:
# YOUR CODE HERE

df['plas'].mean()

np.float64(120.89453125)

Create a new dataframe with only people that are above the mean found in the above cell.

In [13]:
# YOUR CODE HERE

df_2 = df.loc[df['plas'] > df['plas'].mean()]

Create a new dataframe that only includes people who are above the average value for each column in the dataset. In other words, find the average value for each column, and then find which users have values above all of these average column values.

In [15]:
# YOUR CODE HERE

for col in df.columns:
  df_3 = df.loc[df[col] > df[col].mean()]

*Note: the next 3 problems were not explicitly shown in our tutorial—being able to effectively google and look through documentation is a very important coding tool!* ¯\\\_(ツ)_/¯

Ignoring the index (resetting the index to 0) and using the dataframe from the cell above, sort the values based on `"skin"`, `"test"`, and `"pedi"` values in ascending order. Please write this in one line.

In [17]:
# YOUR CODE HERE

df_3.sort_values(by = ['skin', 'test', 'pedi']).reset_index(drop = True)

     preg  plas  pres  skin  test  mass   pedi  age  class
0       1   173    74     0     0  36.8  0.088   38      1
1       6   125    76     0     0  33.8  0.121   54      1
2       3   121    52     0     0  36.0  0.127   25      1
3       6   194    78     0     0  23.5  0.129   59      1
4       8   143    66     0     0  34.9  0.129   41      1
..    ...   ...   ...   ...   ...   ...    ...  ...    ...
263     1   172    68    49   579  42.4  0.702   28      1
264     1   122    90    51   220  49.7  0.325   31      1
265     0   162    76    56   100  53.2  0.759   25      1
266     0   180    78    63    14  59.4  2.420   25      1
267     2   197    70    99     0  34.7  0.575   62      1

[268 rows x 9 columns]

Now let's find the 4 largest values for `"age"`

In [18]:
# YOUR CODE HERE

df['age'].nlargest(4)

459    81
453    72
666    70
123    69
Name: age, dtype: int64

Now find the smallest 4 values for `"pedi"` and `"plas"` in reverse order (smallest to largest).

In [21]:
# YOUR CODE HERE

df['pedi'].nsmallest(4)
df['plas'].nsmallest(4)

75     0
182    0
342    0
349    0
Name: plas, dtype: int64